spring:
  application:
    name: zuul-server
server:
  port: 8762

eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
      defaultZone: http://blog-3-discovery-container:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true 

zuul:
  ignoredServices: '*'
  routes:
    books:
      path: /books/**
#      service-id: books
#      strip-prefix: false
      
management:
  server:
    port: 8763
  endpoints:
    web:
      exposure:
        include: "*"
        
#ribbon:
#  eureka:
#    enabled: false