spring:
  application:
    name: client-books

server:
  port: ${PORT:8090}

eureka:
  client:
    serviceUrl:
      defaultZone: http://blog-3-discovery-container:8761/eureka
#      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
