spring:
  application:
    name: books
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
 
server:
  port: ${PORT:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: http://blog-3-discovery-container:8761/eureka
#      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true