spring:
  application:
    name: zuul-server
server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://blog-3-discovery-container:8761/eureka
  instance:
    preferIpAddress: true 

zuul:
#all services are ignored, except for books
  ignoredServices: '*'
  routes:
    books:
      serviceId: books
      stripPrefix: false