version: '3'
services:
  blog-1-discovery:
    container_name: blog-1-discovery-container
    build:
      context: ./1_discovery_server
    ports:
      - "8761:8761"
    stdin_open: true
    tty: true
    networks:
      - net1
  blog_1_service1:
    container_name: blog_1_service1-container
    build:
      context: ./1_discovery_client
    ports: 
      - "8081:8080"
    stdin_open: true
    tty: true
    networks:
      - net1
    depends_on:
      - blog-1-discovery
  blog_1_service2:
    container_name: blog_1_service2-container
    build:
      context: ./1_discovery_client
    ports: 
      - "8082:8080"
    networks:
      - net1
    depends_on:
      - blog-1-discovery
networks:
  net1:
