version: '3'
services:
  blog-3-books:
    container_name: blog-3-books-container
    build:
      context: ./3_load_balancing_books
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    stdin_open: true
    tty: true
    networks:
      - net1
  blog-3-books2:
    container_name: blog-3-books2-container
    build:
      context: ./3_load_balancing_books
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
    stdin_open: true
    tty: true
    networks:
      - net1
  blog-3-discovery:
    container_name: blog-3-discovery-container
    build:
      context: ./3_load_balancing_discovery
    ports: 
      - "8761:8761"
    # environment:
      # - port=8080        
    stdin_open: true
    tty: true
    networks:
      - net1
  blog-3-zuul:
    container_name: blog-3-zuul-container
    build:
      context: ./3_load_balancing_zuul
    ports: 
      - "8762:8762"
    networks:
      - net1
  blog-3-client:
    container_name: blog-3-client-container
    build:
      context: ./3_load_balancing_client
    ports: 
      - "8090:8090"
    networks:
      - net1
networks:
  net1:
